drop table if exists `MercuPy_1.0-2B`;
create table `MercuPy_1.0-2B` (
dbrunhash char(32) not null,
dbauthor varchar(255),
dbname varchar(255),
dbtemplate varchar(255),
dbdate datetime not null,
TimeUnits varchar(255),
Epoch float,
DtOutput float,
CentralReference varchar(255),
TimeRelativeIntegration varchar(255),
IntegrationAlgorithm varchar(255),
IntegrationAccuracy float,
IntegrationPrecision varchar(255),
IntegrationChangeOver float,
DStepPeriodic int,
StopIntegration varchar(255),
Collisions varchar(255),
SystemDescription text,
CentralName varchar(255),
CentralMass varchar(255),
CentralClass varchar(255),
CentralDensity float,
CentralRadius float,
CentralUnits varchar(255),
CentralState varchar(255),
CentralJ2 float,
CentralJ4 float,
CentralJ6 float,
BodyName varchar(255),
BodyMass varchar(255),
BodyClass varchar(255),
BodyDensity float,
BodyRadius float,
BodyUnits varchar(255),
BodyState varchar(255),
BodyAs varchar(255),
BodySpin varchar(255),
BodyClose float,
ChangeEnergy float,
ChangeMomentum float,
primary key (dbrunhash),
runs_runcode char(8)
);
